### PR TITLE
add support for configurable php versions

### PR DESCRIPTION
**Pull request by ramunasd**
php 7.0 is great, but not always is supported version
btw, 7.1 is released already, so this role could support really latest php version

### CODE REVIEW

**Comment by adamdyson** [comment]
If you can get Travis to pass the build test on CentOS then I'll merge this straight away.

**Comment by ramunasd** [comment]
@adamdyson already fixed

**Comment by adamdyson** [comment]
@ramunasd I've had a chance to look over this pull request again, now that Travis is passing all tests, I'm considering merging these changes tonight but I've got a question concerning multiple PHP-FPM processes of different versions, running and starting at the same time.

Lets assume a person is using this role in a production environment and would like upgrade from version `7.0` to `7.1`. Maybe I'm overthinking this, but for the transition to go smoothly shouldn't the `7.0` service be stopped and disabled from starting up automatically at boot?

Any ideas on how this could be cleanly implemented? Below is an idea I had..

By default the variable `php_old_version` value would be `None`.

```
...
php_version: '7.1'
php_old_version: '7.0'
```

Each of the OS specific variable files (`Debian.yml` & `RedHat.yml`) would define a variable `php_fpm_old_service_name` and the value would depend on whether `php_old_version` has a value or not.

```
...
php_fpm_old_service_name: "{{ None if php_old_version == None else 'php' + php_old_version + '-fpm' "
```

An additional task could be added to the `services.yml` file which stops and disables the `php_fpm_old_service_name` if it has a value.

```
- name: 'PHP | Disable old PHP FPM service.'
  become: yes
  service:
    name: '{{ php_fpm_old_service_name }}'
    state: 'stoppped'
    enabled: no
  when: '{{ php_fpm_old_service_name | default(None) != None }}'
```

**Comment by ramunasd** [comment]
Hey @adamdyson, long time has passed since my fixes. Actually, i think we shouldn't mix together different things into one pull request.
And regarding different php versions - i can't agree that hardcoded "old" php version is good way to go. In this case we need to implement some kind of current version detection and do cleanups before upgrade. But at same time, we can't do cleanups until updated version is not installed and configured properly.

**Comment by adamdyson** [comment]
@ramunasd You'll be happy know this feature has been integrated into the latest version [2.1.1](https://github.com/ontic/ansible-role-php/releases/tag/v2.1.1). Thank you for contributing.

Commit: [22b49037b5193d3ed8c54ce595135d4be3591f96](https://github.com/ontic/ansible-role-php/commit/22b49037b5193d3ed8c54ce595135d4be3591f96)
Commit: [9a77f35c00509f6f596ef1e0b1a1f66d58e94b3](https://github.com/ontic/ansible-role-php/commit/79a77f35c00509f6f596ef1e0b1a1f66d58e94b3)

**Pull request closed without merging**
